"""Stubs for array-api-extra Array type to work with FastSIMUS Array."""

from typing import Any

def isclose(*args: Any, **kwargs: Any) -> Any: ...
def sinc(*args: Any, **kwargs: Any) -> Any: ...
def __getattr__(name: str) -> Any: ...
