name: Benchmark

on:
  push:
    branches:
      - "main"
  pull_request:
    # To limit Actions,
    # don't automatically run on synchronize, but allow manual triggering
    types: [opened, reopened, ready_for_review]
    paths:
      - "**"
      - "!**.md"
      - "!**.rst"
      - "!docs/**"
      - "!.gitignore"
      - "!.github/workflows/*.yml"
      - ".github/workflows/benchmark.yml"
  workflow_dispatch:


jobs:
  benchmark:
    # for now, run on Apple Silicon for mlx
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Run benchmarks
        run: uv run poe benchmark

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          include-hidden-files: true
          path: .benchmarks
          retention-days: 90
