name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch: # Enable manual trigger.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Mandatory for OIDC.
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Run tests
        run: uv run pytest

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish --trusted-publishing always
